/**
 * File Writer Utility
 * 
 * Handles writing solution files to the tasks directory.
 * Creates the required folder structure for each day's task.
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { config } from '../config/index.js';
import { logger } from './logger.js';
import type { Task } from '../taskSelector/types.js';
import type { SolutionStep } from '../splitter/types.js';

const fileLogger = logger.child('FileWriter');

/**
 * Get today's date in YYYY-MM-DD format
 */
export function getTodayDateString(): string {
    const now = new Date();
    const year = now.getFullYear();
    const month = String(now.getMonth() + 1).padStart(2, '0');
    const day = String(now.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
}

/**
 * Get the task directory path for a specific date
 */
export function getTaskDirPath(dateString?: string): string {
    const date = dateString ?? getTodayDateString();
    return path.join(config.tasksDir, date);
}

/**
 * Ensure the task directory exists for today
 */
export async function ensureTaskDir(dateString?: string): Promise<string> {
    const taskDir = getTaskDirPath(dateString);
    await fs.mkdir(taskDir, { recursive: true });
    fileLogger.debug(`Ensured task directory exists: ${taskDir}`);
    return taskDir;
}

/**
 * Write the problem description file (problem.md)
 */
export async function writeProblemFile(task: Task, dateString?: string): Promise<string> {
    const taskDir = await ensureTaskDir(dateString);
    const filePath = path.join(taskDir, 'problem.md');

    const content = `# ${task.title}

## Source
- **Platform**: ${task.source}
- **URL**: ${task.url ?? 'N/A'}
- **Difficulty**: ${task.difficulty}
- **Date**: ${dateString ?? getTodayDateString()}

## Problem Description

${task.description}

## Tags
${task.tags.map(tag => `- ${tag}`).join('\n')}
`;

    await fs.writeFile(filePath, content, 'utf-8');
    fileLogger.info(`Wrote problem file: ${filePath}`);
    return filePath;
}

/**
 * Write a solution step file (solution-step-N.ts)
 */
export async function writeSolutionStepFile(
    step: SolutionStep,
    stepNumber: number,
    dateString?: string
): Promise<string> {
    const taskDir = await ensureTaskDir(dateString);
    const fileName = `solution-step-${stepNumber}.ts`;
    const filePath = path.join(taskDir, fileName);

    const header = `/**
 * Step ${stepNumber}: ${step.name}
 * 
 * ${step.description}
 */

`;

    const content = header + step.code;
    await fs.writeFile(filePath, content, 'utf-8');
    fileLogger.info(`Wrote solution step file: ${filePath}`);
    return filePath;
}

/**
 * Write the final solution file (solution-final.ts)
 */
export async function writeFinalSolutionFile(
    fullCode: string,
    dateString?: string
): Promise<string> {
    const taskDir = await ensureTaskDir(dateString);
    const filePath = path.join(taskDir, 'solution-final.ts');

    const header = `/**
 * Final Solution
 * 
 * Complete implementation with all steps combined.
 * Generated by AutoCoderDaily on ${dateString ?? getTodayDateString()}
 */

`;

    const content = header + fullCode;
    await fs.writeFile(filePath, content, 'utf-8');
    fileLogger.info(`Wrote final solution file: ${filePath}`);
    return filePath;
}

/**
 * Write a test file for the solution
 */
export async function writeTestFile(
    testCode: string,
    dateString?: string
): Promise<string> {
    const taskDir = await ensureTaskDir(dateString);
    const filePath = path.join(taskDir, 'solution.test.ts');

    const header = `/**
 * Test Suite
 * 
 * Auto-generated tests for the daily solution.
 * Generated by AutoCoderDaily on ${dateString ?? getTodayDateString()}
 */

`;

    const content = header + testCode;
    await fs.writeFile(filePath, content, 'utf-8');
    fileLogger.info(`Wrote test file: ${filePath}`);
    return filePath;
}

/**
 * List all files in a task directory
 */
export async function listTaskFiles(dateString?: string): Promise<string[]> {
    const taskDir = getTaskDirPath(dateString);

    try {
        const entries = await fs.readdir(taskDir, { withFileTypes: true });
        return entries
            .filter(entry => entry.isFile())
            .map(entry => path.join(taskDir, entry.name));
    } catch (error) {
        if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
            return [];
        }
        throw error;
    }
}
